# Generated by Django 4.2.2 on 2023-06-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sipalaya', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInfo',
            new_name='ContactInfo',
        ),
    ]
