# Generated by Django 4.2.2 on 2023-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sipalaya', '0004_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
